### ISSUE TITLE
feat: 타이포 그래피 공통 컴포넌트 생성

### ISSUE THREAD

**Issue by skyeome** [TripComeTrue/TripComeTrue_FE#11]
## 세부 내용
텍스트 관련 공통 컴포넌트 생성작업

## TODO-List

- [x] 공통 스타일 관련 변수 작업
- [x] 버튼 컴포넌트 생성
- [x] 하단 Tab 네비게이션 생성
