### ISSUE TITLE
Feat: 여행 일정 복사하기 페이지 작업 및 기능 컴포넌트 보완

### ISSUE THREAD

**Issue by mysdpy30s** [TripComeTrue/TripComeTrue_FE#141]
## 🔎 세부 내용
여행 일정 복사하기 페이지 작업 및 기능 컴포넌트 보완

## 📝 TODO-List
- [ ] 여행 계획 페이지 단계별 validation 추가 (빈칸 있을 시 다음단계 진입 불가)
- [x] 여행 일정 복사하기 페이지 작업
- [x] 계획 또는 후기 작성 후 리다이렉팅 url 추가
