### ISSUE TITLE
refactor: 여행 메인, 여행 상세페이지 에러 핸들링 및 Suspense와 ErrorBoundary 적용

### ISSUE THREAD

**Issue by JiHongkyu** [TripComeTrue/TripComeTrue_FE#167]
## 🔎 세부 내용
여행 메인페이지 타입지정 및 에러 핸들링
여행 메인페이지 Suspense, ErrorBoundary 적용

여행 후기 상세페이지 타입지정 및 에러 핸들링
여행 후기 상세페이지 Suspense, ErrorBoundary 적용

## 📝 TODO-List
- [x] 여행 메인페이지 타입지정 및 에러 핸들링
- [x] 여행 메인페이지 Suspense, ErrorBoundary 적용
- [x] 여행 후기 상세페이지 타입지정 및 에러 핸들링
- [x] 여행 후기 상세페이지 Suspense, ErrorBoundary 적용
