### ISSUE TITLE
feat: 로그인 / 회원가입 api 연동

### ISSUE THREAD

**Issue by skyeome** [TripComeTrue/TripComeTrue_FE#23]
## 세부 내용
api 명세서 내용 참고하여 로그인 / 회원가입 기능을 추가 합니다.

## TODO-List

- [ ] 이메일 중복 체크 api 연동
- [ ] 소셜 로그인 / 이메일 로그인 api 연동
- [ ] 회원가입 api 연동
