### ISSUE TITLE
style: Creator/Review UI 공통 컴포넌트화 

### ISSUE THREAD

**Issue by seacrab808** [TripComeTrue/TripComeTrue_FE#37]
## 세부 내용
- Creator
<img width="334" alt="스크린샷 2024-01-11 오후 6 18 08" src="https://github.com/TripComeTrue/TripComeTrue_FE/assets/93272421/fe14d7a9-2fb3-4361-8454-dcaea13beee4">

이거나

<img width="335" alt="스크린샷 2024-01-11 오후 6 19 05" src="https://github.com/TripComeTrue/TripComeTrue_FE/assets/93272421/7b0a558c-8845-40b0-8ad0-c677b40a7c24">

- Review
<img width="335" alt="스크린샷 2024-01-11 오후 6 19 05" src="https://github.com/TripComeTrue/TripComeTrue_FE/assets/93272421/e17c3744-a7e8-4a17-977f-5070f2ff3d42">

이 부분에 사용할 수 있는 컴포넌트를 공통화 하려고 합니다.

## TODO-List
- [x] Creator 공통 컴포넌트 생성
- [x] Creator  props - 별점 유무에 따라 디자인 다르게 
- [x] 노션에 Creator 사용법 추가
- [x] Review 공통 컴포넌트 생성
- [x] Review props/type정의
- [ ] 노션에 Review 사용법 추가
