### ISSUE TITLE
style: 여행 일정 상세페이지, 리뷰, 댓글 UI 구현

### ISSUE THREAD

**Issue by JiHongkyu** [TripComeTrue/TripComeTrue_FE#44]
## 세부 내용
여행 일정 상세페이지 UI 작업
리뷰 UI 작업
댓글 UI 작업

## TODO-List
- [x] 여행 일정 상세페이지 UI 작업
- [x] 리뷰 UI 작업
- [x] 댓글 UI 작업
