### ISSUE TITLE
style: 검색 페이지 라우팅 및 UI (1차)

### ISSUE THREAD

**Issue by seacrab808** [TripComeTrue/TripComeTrue_FE#46]
## 세부 내용
검색 페이지 라우팅 및 UI

## TODO-List

- [ ] 검색 페이지 라우팅 ( 아래 세부는 다 라우팅입니다)
  - [x] search 기본 페이지 라우팅
  - [x] 검색 후 전체 | 도시 | 여행지 | 크리에이터 라우팅
  - [x] 검색 - 전체 페이지
  - [ ] 검색 - 전체 페이지 검색 결과 없는 경우 (후자로 할 듯)
  - [x] 검색 - 도시 페이지
  - [x] 검색 - 여행지 페이지
  - [x] 검색 - 크리에이터 페이지
  - [ ] 크리에이터 더보기 페이지
  - [ ] 크리에이터 상세 페이지
  - [ ] 태그 검색어 페이지
  - [ ] 금액대별 페이지
 
- [x] 검색 결과가 없을 경우에 표출되는 화면이 두 개라서 확인 필요
- [x] search 검색 + 탭바 UI
- [x] /seach 페이지 카테고리 선택 UI
