### ISSUE TITLE
style: 여행태그종류 모달, 해시태그 등록, 상세피드 헤더 컴포넌트 제작

### ISSUE THREAD

**Issue by skyeome** [TripComeTrue/TripComeTrue_FE#47]
## 세부 내용
**해시태그 등록 컴포넌트**
![image](https://github.com/TripComeTrue/TripComeTrue_FE/assets/59966217/6da4707b-e57c-4a9a-879f-5c20256e7bcf)

**여행태그종류 모달**
![image](https://github.com/TripComeTrue/TripComeTrue_FE/assets/59966217/e1f220d8-fb5d-40a7-81b1-5ba15ec063a1)

**상세피드 헤더**
![image](https://github.com/TripComeTrue/TripComeTrue_FE/assets/59966217/dedec390-4b0f-4df6-993a-be0532235bf8)

## TODO-List

- [x] 해시태그 등록 컴포넌트 제작
- [x] 여행태그종류 모달 제작
- [x] 상세피드 헤더 제작
