### ISSUE TITLE
style: 여행지 상세 피드 레이아웃

### ISSUE THREAD

**Issue by Eojoonhyuk** [TripComeTrue/TripComeTrue_FE#50]
## 세부 내용
여행지 상세 피드 레이아웃

## TODO-List

- [x] 갤러리
- [ ] 리뷰
- [x] 여행지 위치 맵, 기본 정보
- [x] 근처 추천 여행지
- [x] 여행 후기 Top 3
