### ISSUE TITLE
style: 검색 페이지 UI (2차)

### ISSUE THREAD

**Issue by seacrab808** [TripComeTrue/TripComeTrue_FE#57]
## 세부 내용
city / spot / creator 컴포넌트를 만들고 all에 합치는 UI 작업과 검색어가 없을 경우 예외 처리 작업을 진행할 예정이다.

## TODO-List

- [x] city 컴포넌트 UI
- [x] spot 컴포넌트 UI
- [x] creator 컴포넌트 UI
- [x] all에 컴포넌트 합치기
