### ISSUE TITLE
feat: home 페이지 퍼블리싱 (2차)

### ISSUE THREAD

**Issue by seacrab808** [TripComeTrue/TripComeTrue_FE#6]
## 세부 내용
지난 작업 이어서 화면 크기 조정 후 나머지 home 부분 퍼블리싱 진행하겠습ㅂ니다.

## TODO-List

- [x]  화면 크기 조정..
- [x]  homeHotplace 페이지 작업
- [x]  homeCreator 페이지 작업
