### ISSUE TITLE
feat: 온보딩 추가, 로그인 / 회원가입 api 수정

### ISSUE THREAD

**Issue by skyeome** [TripComeTrue/TripComeTrue_FE#70]
## 세부 내용
온보딩 페이지 디자인을 보고 퍼블리싱을 진행하고, api 폴더로 기존 코드를 이동하고 버그를 수정합니다.

## TODO-List

- [x] 온보딩 페이지 퍼블리싱
- [x] api 폴더로 기존 api 코드 이동
- [x] 아이디 중복확인 버그 수정
