### ISSUE TITLE
bugfix: 회원가입 페이지 버그 수정

### ISSUE THREAD

**Issue by skyeome** [TripComeTrue/TripComeTrue_FE#98]
## 세부 내용
회원가입 페이지의 버그를 수정합니다.

## TODO-List

- [x] 회원가입 버그 수정
- [x] 회원가입 후 웰컴페이지 로직 수정
- [x] 아이디 > 이메일로 수정
